### PR TITLE
I had to revert your 2 last commits and then merge them again, it has been hard to get this working xD

### PR DESCRIPTION
**Pull request by muriplz**

### CODE REVIEW

**Comment by muriplz** [comment]
lots of your new stuff is changed because github is confusing, gimme time to review all this, lots of the new lines got reverted idk why

**Comment by FrannDzs** [comment]
@muriplz Hello, good morning, I don't understand what you did here, these are changes that were already made... Which lines do you think are wrong? Mark them instead, with a comment. To update the fork you must click on Fetch up stream.

**Comment by muriplz** [comment]
Yeah, the problem is bc i started to reviws it and you continued commiting, all the latest changes you did are not on my side, i tried (literally like 100 times) to fetch ur upstream, i understand perfectly how that works but still is confusing how its actually executed, where can i correct my file?

**Comment by FrannDzs** [comment]
> Yeah, the problem is bc i started to reviws it and you continued commiting, all the latest changes you did are not on my side, i tried (literally like 100 times) to fetch ur upstream, i understand perfectly how that works but still is confusing how its actually executed, where can i correct my file?

Hello, you must delete all forks to create, redo a fork from my create profile, and download the file en_en.json. Then you test it in the create.jar. When you find an error, mostly in the syntax of the ponder section, you make the changes in Github in your profile, which would be a copy of my repository, in the file es_es.json directly... Is this understood? Maybe we should talk on discord, it's easier :)

**Comment by muriplz** [comment]
can you add me? muriplz#8790

**Pull request closed without merging**
